---
  - name: Get Docker GPG key
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: Get more packages
    apt:
      name: ['linux-image-extra-virtual', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python-setuptools']
      state: present

  - name: Add Docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ hostvars[inventory_hostname].ansible_distribution_release}} stable
      state: present
      update_cache: yes

  - name: Get Docker
    apt:
      name: ['docker-ce', 'docker-compose', 'python-docker']
      state: present

  - name: Get Pip
    apt: name=python-pip state=present
  
  - name: Get docker for pip
    pip:
      name: docker
      state: latest
